package com.dp.test.dao.intr;

import com.dp.test.domain.Hotel;

public interface HotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbggenerated
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbggenerated
     */
    int insertSelective(Hotel record);
}